import nodemailer from 'nodemailer';
export default async function handler(req, res) {
    let testAccount = await nodemailer.createTestAccount();
    const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: 'cs20b057@iittp.ac.in',
                pass: 'EnterPasswordHere'
            }
    });
    let info = await transporter.sendMail({
        from: 'cs20b057@iittp.ac.in', // sender address
        to: "sirish1527@gmail.com", // list of receivers
        subject: "Autogenerated email", // Subject line
        text: "Hello world!", // plain text body
      },function(err,data){
        if(err){
            res.send("error",500);
        }
        else{
            res.send("success",200);
        }
        });
}   